### PR TITLE
update pytest command

### PR DESCRIPTION
**Pull request by buijennifer**

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]
👍

**Comment by mrakitin** [comment]
I think for this package we will have to exclude the pytest testing as the `test.py` is not included in the PyPI source distribution. Check it's contents from https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz. That's the project's contents:
```
.
├── LICENSE
├── MANIFEST.in
├── PKG-INFO
├── README.rst
├── netifaces.c
├── netifaces.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── top_level.txt
│   └── zip-safe
├── setup.cfg
└── setup.py
```

**Comment by mrakitin** [comment]
If you look closer to https://github.com/al45tair/netifaces/blob/master/test.py, it is not a *pytest* test. However, it can be run with `python test.py` or `{{ PYTHON }} test.py`, once it's available in the next release. For now, I suggest to remove that test command, but keep the `import netifaces` part.

**Comment by buijennifer** [comment]
> If you look closer to https://github.com/al45tair/netifaces/blob/master/test.py, it is not a _pytest_ test. However, it can be run with `python test.py` or `{{ PYTHON }} test.py`, once it's available in the next release. For now, I suggest to remove that test command, but keep the `import netifaces` part.

**Comment by buijennifer** [comment]
I see. Thank you for pointing that out. I will update the recipe accordingly.

**Comment by mrakitin** [comment]
See https://github.com/al45tair/netifaces/pull/44 with the proposed changes.

**Pull request merged**
